name: E2E Tests

on:
  push:
    branches: [ maint/e2e-readiness ]
  pull_request:
    branches: [ maint/e2e-readiness ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build application
      run: npm run build
      
    - name: Seed E2E test data
      run: deno run --allow-all scripts/e2e-seed.ts
      env:
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
    - name: Run Playwright tests
      run: npx playwright test
      env:
        E2E_BASE_URL: http://localhost:5173
        
    - name: Run Edge Functions smoke tests
      run: deno run --allow-all scripts/e2e-smoke.ts
      env:
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
    - name: Cleanup test data
      run: deno run --allow-all scripts/e2e-clean.ts
      env:
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      if: always()
      
    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30